"""AUTO-GENERATED by scripts/export_garda_coeffs.py — do not edit.

Trained on ERA5 features 2012-2026 (n=2972 season days, labels from Meteotrentino T0193);
thresholds calibrated on previous_day1 forecast features (n=513).
Data provenance and licences: DATA_SOURCES.md.
"""

ORA = {
  "features": [
    "dp_bz_morn",
    "dp_ib_morn",
    "dp_ib_trend",
    "dtmax_ve_ib",
    "solar_morn",
    "cloud_morn",
    "rh_morn",
    "precip_day",
    "w100_noon",
    "w100_u",
    "w100_v",
    "tmax_tor"
  ],
  "mean": [
    2.019428,
    3.175545,
    -1.773295,
    3.923654,
    566.431359,
    58.288214,
    84.779475,
    1.941487,
    6.460209,
    -1.087621,
    4.014423,
    23.767699
  ],
  "std": [
    1.22559,
    2.90655,
    1.827824,
    3.498772,
    184.133472,
    31.105179,
    8.930946,
    4.68453,
    2.663227,
    3.64343,
    4.272468,
    5.056942
  ],
  "coef": [
    -0.591956,
    0.416091,
    -0.221779,
    -0.036131,
    0.503249,
    -0.445118,
    -0.090636,
    -0.62597,
    -0.025415,
    -0.069397,
    0.823286,
    0.199518
  ],
  "intercept": 0.207066,
  "platt_a": 0.789868,
  "platt_b": -0.592607,
  "threshold_go": 0.689,
  "threshold_maybe": 0.539
}

PELER = {
  "features": [
    "dp_ib_night",
    "dp_bz_night",
    "cloud_night",
    "precip_night",
    "w100_night",
    "solar_prev_pm",
    "rh_night",
    "dp_ib_morn",
    "dtmax_ve_ib"
  ],
  "mean": [
    3.313809,
    1.963304,
    63.850606,
    1.727591,
    4.530754,
    646.988896,
    87.341184,
    3.175545,
    3.923654
  ],
  "std": [
    3.002433,
    1.294954,
    31.268713,
    4.628198,
    2.426872,
    170.051774,
    10.54212,
    2.90655,
    3.498772
  ],
  "coef": [
    -0.587609,
    1.290189,
    -0.225512,
    -0.284354,
    -0.290909,
    -0.148383,
    0.42874,
    0.526477,
    -0.210601
  ],
  "intercept": -0.002514,
  "platt_a": 1.57171,
  "platt_b": 1.967853,
  "threshold_go": 0.562,
  "threshold_maybe": 0.412
}
