"""Train the Ora/Peler logistics and freeze them into src/garda/coeffs.py.

Training features are built through garda.features (the SAME pure-Python
builder the dashboard serves with), from the stored ERA5 JSONs. Verdict
thresholds are calibrated on previous_day1 forecast features (2024+), because
that is the distribution the live dashboard scores — see the transfer test in
docs/findings/garda-feasibility-spike-2026-07-05.md (Addendum 2).

Needs the [ml] extra. Rerun after label or feature changes; the golden vector
in tests/test_garda.py will flag the diff.
"""

import json
import sys
from datetime import date
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
from garda.features import ORA_FEATURES, PELER_FEATURES, PointSeries, build_day_features  # noqa: E402

GARDA = ROOT / "data"


def load_points(subdir: str) -> dict[str, PointSeries]:
    return {
        name: PointSeries(json.loads((GARDA / subdir / f"{name}.json").read_text())["hourly"])
        for name in ("torbole", "verona", "bolzano", "innsbruck")
    }


def feature_frame(subdir: str, labels: pd.DataFrame) -> pd.DataFrame:
    points = load_points(subdir)
    rows = []
    for _, r in labels.iterrows():
        day: date = r["date"].date()
        f = build_day_features(points, day)
        if f is None:
            continue
        f.update(date=day, year=day.year, month=day.month, ora=r["ora"], peler=r["peler"])
        rows.append(f)
    return pd.DataFrame(rows)


def peirce(y: np.ndarray, yh: np.ndarray) -> float:
    tp = ((y == 1) & (yh == 1)).sum()
    fn = ((y == 1) & (yh == 0)).sum()
    fp = ((y == 0) & (yh == 1)).sum()
    tn = ((y == 0) & (yh == 0)).sum()
    return (tp / (tp + fn) if tp + fn else 0.0) - (fp / (fp + tn) if fp + tn else 0.0)


def main() -> None:
    labels = pd.read_csv(GARDA / "labels.csv", parse_dates=["date"])
    era = feature_frame("era5", labels)
    fc = feature_frame("prevruns", labels)
    print(f"training days (ERA5): {len(era)} | calibration days (previous_day1): {len(fc)}")

    blocks = {}
    for target, feats in (("ora", ORA_FEATURES), ("peler", PELER_FEATURES)):
        X = era[feats].to_numpy(dtype=float)
        y = era[target].to_numpy(dtype=int)
        mean, std = X.mean(axis=0), X.std(axis=0)
        m = LogisticRegression(class_weight="balanced", max_iter=3000)
        m.fit((X - mean) / std, y)

        # Platt-recalibrate probabilities on the forecast-feature distribution
        # (the live dashboard scores forecast data; raw ERA5-trained probs are
        # miscalibrated there — see transfer test) and pick the GO threshold
        # (best Peirce) in CALIBRATED space so displayed % and verdict agree.
        Xc = (fc[feats].to_numpy(dtype=float) - mean) / std
        pc = m.predict_proba(Xc)[:, 1]
        yc = fc[target].to_numpy(dtype=int)
        logit = np.log(pc / (1 - pc)).reshape(-1, 1)
        platt = LogisticRegression(max_iter=1000).fit(logit, yc)
        a, b = float(platt.coef_[0][0]), float(platt.intercept_[0])
        p_cal = 1 / (1 + np.exp(-(a * logit[:, 0] + b)))
        ts = np.quantile(p_cal, np.linspace(0.05, 0.95, 37))
        t_go = float(max(ts, key=lambda t: peirce(yc, (p_cal >= t).astype(int))))
        print(
            f"{target}: platt a={a:.3f} b={b:.3f} | threshold_go={t_go:.3f} "
            f"(Peirce {peirce(yc, (p_cal >= t_go).astype(int)):+.3f} on n={len(yc)})"
        )

        blocks[target] = {
            "features": feats,
            "mean": [round(float(v), 6) for v in mean],
            "std": [round(float(v), 6) for v in std],
            "coef": [round(float(v), 6) for v in m.coef_[0]],
            "intercept": round(float(m.intercept_[0]), 6),
            "platt_a": round(a, 6),
            "platt_b": round(b, 6),
            "threshold_go": round(t_go, 3),
            "threshold_maybe": round(max(0.05, t_go - 0.15), 3),
        }

    out = ROOT / "src" / "garda" / "coeffs.py"
    body = (
        '"""AUTO-GENERATED by scripts/export_garda_coeffs.py — do not edit.\n\n'
        f"Trained on ERA5 features {era.year.min()}-{era.year.max()} "
        f"(n={len(era)} season days, labels from Meteotrentino T0193);\n"
        f"thresholds calibrated on previous_day1 forecast features (n={len(fc)}).\n"
        "Data provenance and licences: DATA_SOURCES.md.\n"
        '"""\n\n'
        f"ORA = {json.dumps(blocks['ora'], indent=2)}\n\n"
        f"PELER = {json.dumps(blocks['peler'], indent=2)}\n"
    )
    out.write_text(body.replace("true", "True").replace("false", "False"))
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
